[tasks.watch]
run_task = [
  { name = ["clippy", "test", "run"] }
]
watch = true

[tasks.watch.paths]
paths = ["src/**/*"]

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.run]
command = "cargo"
args = ["run"]